### ISSUE TITLE
Recovered images from Gibson

### ISSUE THREAD

**Issue by jdiazram** [wz0919/ScaleVLN#11]
Hi, super nice job.
Did you share the recovered images from Gibson? Because in this [link](https://www.dropbox.com/sh/c34vmieg2g4g6wo/AACPdAsM1E3jcrkeS4dOGC3ga?e=1&dl=0), I only found Recovered Images from hm3d. 

Can you share the recovered images from Gibson?

Thx

**Comment by wz0919** [comment]
Thanks for your question. You can find it here
https://www.dropbox.com/scl/fo/29rrldccmxb0ggk5423q8/ACEt9upglxaXug1WjcJrjPg?rlkey=reipcz1h5stkbj026wnn2dqzd&st=9gfxjc2p&dl=0
