### ISSUE TITLE
Release of EnvDrop Speaker

### ISSUE THREAD

**Issue by honghd16** [wz0919/ScaleVLN#8]
Hi, thanks for sharing such a great work!
I am wondering if it is possible to share the weights of the Speaker to generate navigational instructions in ScaleVLN.
I followed the paper to train an EnvDrop Speaker with the clip feature provided on the R2R dataset. However, when generating the instructions for HM3D environments with the provided feature, the results are much worse than the instructions in ScaleVLN.
Could I know what the problem is or is there any plan to release your trained speaker?
Thanks!

**Comment by jdiazram** [comment]
Hi, how did you solve your problem? I need to find the navigational instructions for hm3d (no instr_encoding; I need text), but I need to know which annotation file it is to use habitat-matterport3d. Maybe `r2r_preprocess_data/annotations/pretrain_map/R2R_hm3d_aug_envdrop_generated_enc.jsonl` ?
Thx

**Comment by honghd16** [comment]
> Hi, how did you solve your problem? I need to find the navigational instructions for hm3d (no instr_encoding; I need text), but I need to know which annotation file it is to use habitat-matterport3d. Maybe `r2r_preprocess_data/annotations/pretrain_map/R2R_hm3d_aug_envdrop_generated_enc.jsonl` ? Thx

Hi, the instructions in my version for HM3D and Gibson are in the `annotation` folder with the name `R2R_scalevln_ft_aug_enc.json`. But the repo was updated last month and I just found the link to the dataset has been modified to a HuggingFace link with only the connectivity files. Maybe the `r2r_preprocess_data/annotations/pretrain_map/R2R_hm3d_aug_envdrop_generated_enc.jsonl' is the same as what I use but I am not sure since my version doesn't contain such a file. You may need to contact the authors.
