### ISSUE TITLE
The links to data and features

### ISSUE THREAD

**Issue by woyut** [wz0919/ScaleVLN#9]
Hi, thank you for the nice project! I note that some of the links provided in the readme file are broken, such as https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/scalevln/r2r_preprocess_data.zip and https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/scalevln/features.zip. Could you please repair them? Thank you very much!

**Comment by wz0919** [comment]
Hi, you can access the data here.

https://huggingface.co/datasets/OpenGVLab/ScaleVLN/tree/main

**Comment by woyut** [comment]
Thanks a lot!

**Comment by woyut** [comment]
Hi! I notice the [rvr_data.zip](https://huggingface.co/datasets/OpenGVLab/ScaleVLN/blob/main/rvr_data.zip) file at the huggingface repo. Could you please explain more about how we can read the .mdb files under "REVERIE/features/" ? Also, it seems that "REVERIE/annotations/BBoxes.json" contains only the bounding boxes in the original REVERIE dataset, so where how can we get access to the boxes in the new dataset?
